version: "3.8"
services:
  # api 설정
  bookmarker-api:
    build:
      context: bookmarker-api
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILE_ACTIVE: docker
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_DATASOURCE_URL: jdbc:postgresql://bookmarker-db:5432/appdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "18080:8080"
    # 꺼져도 다시 실행
    restart: always
    # 위 db랑 연결
    depends_on:
      - bookmarker-db