spring:
  application:
    name: bookmarker-api
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    locations: classpath:/db/migration/{vendor} # ???? db ??

---

spring:
  config:
    activate:
      on-profile: k8s
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.h2.H2ConsoleAutoConfiguration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
