spring:
  application:
    name: bookmarker-api
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    locations: classpath:/db/migration/{vendor} # 자동으로 db 설정

---

spring:
  config:
    activate:
      on-profile: k8s
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:appdb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
